# Generated by Django 3.1.7 on 2021-04-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='mptt_level',
            new_name='level',
        ),
    ]
